const cv = "../data/chapter_verses/"

module.exports = {
    Genesis: require(cv + "genesis"),
    Exodus: require(cv + "exodus"),
    Leviticus: require(cv + "leviticus"),
    Numbers: require(cv + "numbers"),
    Deuteronomy: require(cv + "deuteronomy"),
    Joshua: require(cv + "joshua"),
    Judges: require(cv + "judges"),
    Ruth: require(cv + "ruth"),
    "1 Samuel": require(cv + "1samuel"),
    "2 Samuel": require(cv + "2samuel"),
    "1 Kings": require(cv + "1kings"),
    "2 Kings": require(cv + "2kings"),
    "1 Chronicles": require(cv + "1chronicles.js"),
    "2 Chronicles": require(cv + "2chronicles.js"),
    Ezra: require(cv + "ezra.js"),
    Nehemiah: require(cv + "nehemiah"),
    Esther: require(cv + "esther.js"),
    Job: require(cv + "job"),
    Psalms: require(cv + "psalms"),
    Proverbs: require(cv + "proverbs"),
    Ecclesiastes: require(cv + "ecclesiastes"),
    "Song of Songs": require(cv + "songs"),
    "Song of Solomon": require(cv + "songs"),
    Isaiah: require(cv + "isaiah"),
    Jeremiah: require(cv + "jeremiah"),
    Lamentations: require(cv + "lamentations"),
    Ezekiel: require(cv + "ezekiel"),
    Daniel: require(cv + "daniel"),
    Hosea: require(cv + "hosea"),
    Joel: require(cv + "joel"),
    Amos: require(cv + "amos"),
    Jonah: require(cv + "jonah"),
    Micah: require(cv + "micah"),
    Nahum: require(cv + "nahum"),
    Habakkuk: require(cv + "habakkuk.js"),
    Zephaniah: require(cv + "zephaniah"),
    Haggai: require(cv + "haggai"),
    Zechariah: require(cv + "zechariah"),
    Malachi: require(cv + "malachi"),
    Matthew: require(cv + "matthew"),
    Mark: require(cv + "mark"),
    Luke: require(cv + "luke"),
    John: require(cv + "john"),
    Acts: require(cv + "acts"),
    Romans: require(cv + "romans"),
    "1 Corinthians": require(cv + "1corinthians"),
    "2 Corinthians": require(cv + "2corinthians"),
    Galatians: require(cv + "galatians"),
    Ephesians: require(cv + "ephesians"),
    Philippians: require(cv + "philippians"),
    Colossians: require(cv + "colossians"),
    "1 Thessalonians": require(cv + "1thessalonians"),
    "2 Thessalonians": require(cv + "2thessalonians"),
    "1 Timothy": require(cv + "1timothy"),
    "2 Timothy": require(cv + "2timothy"),
    Titus: require(cv + "titus"),
    Hebrews: require(cv + "hebrews"),
    James: require(cv + "james"),
    "1 Peter": require(cv + "1peter"),
    "2 Peter": require(cv + "2peter"),
    "1 John": require(cv + "1john"),
    Revelation: require(cv + "revelation"),
    Tobit: require(cv + "tobit"),
    Judith: require(cv + "judith"),
    "Wisdom of Solomon": require(cv + "wisdomofsolomon"),
    Sirach: require(cv + "sirach"),
    Baruch: require(cv + "baruch"),
    "1 Esdras": require(cv + "1esdras"),
    "1 Maccabees": require(cv + "1maccabees"),
    "2 Maccabees": require(cv + "2maccabees"),
    "3 Maccabees": require(cv + "3maccabees"),
    "4 Maccabees": require(cv + "4maccabees"),
}
