const abbrevations = {
    Gen: "Genesis",
    Ge: "Genesis",
    Gn: "Genesis",
    Ex: "Exodus",
    Exo: "Exodus",
    Exod: "Exodus",
    Lev: "Leviticus",
    Le: "Leviticus",
    Lv: "Leviticus",
    Num: "Numbers",
    Nu: "Numbers",
    Nb: "Numbers",
    Nm: "Numbers",
    Deut: "Deuteronomy",
    De: "Deuteronomy",
    Dt: "Deuteronomy",
    Josh: "Joshua",
    Jos: "Joshua",
    Jsh: "Joshua",
    Judg: "Judges",
    Jdg: "Judges",
    Jg: "Judges",
    Jdg: "Judges",
    Ruth: "Ruth",
    Rth: "Ruth",
    Ru: "Ruth",
    "1Sam": "1 Samuel",
    "1Sam": "1 Samuel",
    "1Sa": "1 Samuel",
    "1S": "1 Samuel",
    "1 Sam": "1 Samuel",
    "1 Sm": "1 Samuel",
    "1 Sa": "1 Samuel",
    "1 S": "1 Samuel",
    "2 Sam": "2 Samuel",
    "2 Sm": "2 Samuel",
    "2 Sa": "2 Samuel",
    "2 S": "2 Samuel",
    "II Sam": "2 Samuel",
    "II Sa": "2 Samuel",
    "2Sam": "2 Samuel",
    "2Sm": "2 Samuel",
    "2Sa": "2 Samuel",
    "2S": "2 Samuel",
    "1Kgs": "1 Kings",
    "1 Kgs": "1 Kings",
    "1Kgs": "1 Kings",
    "1 Ki": "1 Kings",
    "1Ki": "1 Kings",
    "1Kin": "1 Kings",
    "1 Kin": "1 Kings",
    "1 Ki": "1 Kings",
    "1K": "1 Kings",
    "1 K": "1 Kings",
    "2 Kgs": "2 Kings",
    "2 Ki": "2 Kings",
    "2Kgs": "2 Kings",
    "2Kin": "2 Kings",
    "2Ki": "2 Kings",
    "2K": "2 Kings",
    "2 K": "2 Kings",
    "1 Chron": "1 Chronicles",
    "1 Chr": "1 Chronicles",
    "1 Ch": "1 Chronicles",
    "1Chron": "1 Chronicles",
    "1Chr": "1 Chronicles",
    "1Ch": "1 Chronicles",
    "I Chron": "1 Chronicles",
    "I Chr": "1 Chronicles",
    "I Ch": "1 Chronicles",
    "1st Chron": "1 Chronicles",
    "2 Chron": "2 Chronicles",
    "2 Chr": "2 Chronicles",
    "2 Ch": "2 Chronicles",
    "2Chron": "2 Chronicles",
    "2Chr": "2 Chronicles",
    "2Ch": "2 Chronicles",
    "II Chron": "2 Chronicles",
    "II Chr": "2 Chronicles",
    "II Ch": "2 Chronicles",
    Ezra: "Ezra",
    Ezr: "Ezra",
    Ez: "Ezra",
    Neh: "Nehemiah",
    Ne: "Nehemiah",
    Esth: "Esther",
    Est: "Esther",
    Es: "Esther",
    Job: "Job",
    Jb: "Job",
    Ps: "Psalms",
    Psalm: "Psalms",
    Pslm: "Psalms",
    Psa: "Psalms",
    Psm: "Psalms",
    Pss: "Psalms",
    Prov: "Proverbs",
    Pro: "Proverbs",
    Prv: "Proverbs",
    Pr: "Proverbs",
    Eccl: "Ecclesiastes",
    Eccles: "Ecclesiastes",
    Eccle: "Ecclesiastes",
    Ecc: "Ecclesiastes",
    Ec: "Ecclesiastes",
    Qoh: "Ecclesiastes",
    Song: "Song of Songs",
    SOS: "Song of Songs",
    So: "Song of Songs",
    Cant: "Song of Songs",
    Isa: "Isaiah",
    Is: "Isaiah",
    Jer: "Jeremiah",
    Je: "Jeremiah",
    Lam: "Lamentations",
    La: "Lamentations",
    Ezek: "Ezekiel",
    Eze: "Ezekiel",
    Ezk: "Ezekiel",
    Dan: "Daniel",
    Da: "Daniel",
    Dn: "Daniel",
    Hos: "Hosea",
    Ho: "Hosea",
    Joel: "Joel",
    Jl: "Joel",
    Amos: "Amos",
    Am: "Amos",
    Ob: "Obadiah",
    Obad: "Obadiah",
    Jonah: "Jonah",
    Jnh: "Jonah",
    Jon: "Jonah",
    Mic: "Micah",
    Mc: "Micah",
    Nah: "Nahum",
    Na: "Nahum",
    Hb: "Habakkuk",
    Hab: "Habakkuk",
    Zeph: "Zephaniah",
    Zep: "Zephaniah",
    Zp: "Zephaniah",
    Hag: "Haggai",
    Hg: "Haggai",
    Zech: "Zechariah",
    Zec: "Zechariah",
    Zc: "Zechariah",
    Mal: "Malachi",
    Ml: "Malachi",
    Matt: "Matthew",
    Mark: "Mark",
    Luke: "Luke",
    John: "John",
    Acts: "Acts",
    Act: "Acts",
    Rom: "Romans",
    R: "Romans",
    "1Cor": "1 Corinthians",
    "2Cor": "2 Corinthians",
    Gal: "Galatians",
    Eph: "Ephesians",
    Phil: "Philippians",
    Col: "Colossians",
    "1Thess": "1 Thessalonians",
    "2Thess": "2 Thessalonians",
    "1Tim": "1 Timothy",
    "2Tim": "2 Timothy",
    Titus: "Titus",
    Phlm: "Philemon",
    Heb: "Hebrews",
    Jas: "James",
    "1Pet": "1 Peter",
    "2Pet": "2 Peter",
    "1John": "1 John",
    "2John": "2 John",
    "3John": "3 John",
    Jude: "Jude",
    Rev: "Revelation",
    Mt: "Matthew",
    Mc: "Mark",
    L: "Luke",
    J: "John",
    Act: "Acts",
    R: "Romans",
    "1K": "1 Corinthians",
    "2K": "2 Corinthians",
    G: "Galatians",
    E: "Ephesians",
    Ph: "Philippians",
    Kol: "Colossians",
    "1Th": "1 Thessalonians",
    "2Th": "2 Thessalonians",
    "1T": "1 Timothy",
    "2T": "2 Timothy",
    Tt: "Titus",
    Phm: "Philemon",
    H: "Hebrews",
    Jc: "James",
    "1P": "1 Peter",
    "2P": "2 Peter",
    "1J": "1 John",
    "2J": "2 John",
    "3J": "3 John",
    Jd: "Jude",
    Ap: "Revelation",
}

module.exports = abbrevations