const abbrevations = {
    Gen: "Genesis",
    Ge: "Genesis",
    Gn: "Genesis",
    Ex: "Exodus",
    Exo: "Exodus",
    Exod: "Exodus",
    Lev: "Leviticus",
    Le: "Leviticus",
    Lv: "Leviticus",
    Num: "Numbers",
    Nu: "Numbers",
    Nb: "Numbers",
    Nm: "Numbers",
    Deut: "Deuteronomy",
    De: "Deuteronomy",
    Dt: "Deuteronomy",
    Josh: "Joshua",
    Jos: "Joshua",
    Jsh: "Joshua",
    Judg: "Judges",
    Jdg: "Judges",
    Jg: "Judges",
    Jdg: "Judges",
    Ruth: "Ruth",
    Rth: "Ruth",
    Ru: "Ruth",
    "1Sam": "1 Samuel",
    "1sam": "1 Samuel",
    "1SA": "1 Samuel",
    "1sa": "1 Samuel",
    "1 SAM": "1 Samuel",
    "1 sam": "1 Samuel",
    "1 sm": "1 Samuel",
    "1 sa": "1 Samuel",
    "1 s": "1 Samuel",
    "2 Sam": "2 Samuel",
    "2 sam": "2 Samuel",
    "2SA": "2 Samuel",
    "2sa": "2 Samuel",
    "2 SAM": "2 Samuel",
    "2 sam": "2 Samuel",
    "2 sm": "2 Samuel",
    "2 sa": "2 Samuel",
    "2 s": "2 Samuel",
    "II SAM": "2 Samuel",
    "ii sam": "2 Samuel",
    "II SA": "2 Samuel",
    "ii sa": "2 Samuel",
    "2SAM": "2 Samuel",
    "2sam": "2 Samuel",
    "2SM": "2 Samuel",
    "2sm": "2 Samuel",
    "2SA": "2 Samuel",
    "2sa": "2 Samuel",
    "1Kgs": "1 Kings",
    "1 Kgs": "1 Kings",
    "1Kgs": "1 Kings",
    "1 Ki": "1 Kings",
    "1Ki": "1 Kings",
    "1Kin": "1 Kings",
    "1 Kin": "1 Kings",
    "1 Ki": "1 Kings",
    "1K": "1 Kings",
    "1 K": "1 Kings",
    "2 Kgs": "2 Kings",
    "2 Ki": "2 Kings",
    "2Kgs": "2 Kings",
    "2Kin": "2 Kings",
    "2Ki": "2 Kings",
    "2K": "2 Kings",
    "2 K": "2 Kings",
    "1 Chron": "1 Chronicles",
    "1 Chr": "1 Chronicles",
    "1 Ch": "1 Chronicles",
    "1Chron": "1 Chronicles",
    "1Chr": "1 Chronicles",
    "1Ch": "1 Chronicles",
    "I Chron": "1 Chronicles",
    "I Chr": "1 Chronicles",
    "I Ch": "1 Chronicles",
    "1st Chron": "1 Chronicles",
    "2 Chron": "2 Chronicles",
    "2 Chr": "2 Chronicles",
    "2 Ch": "2 Chronicles",
    "2Chron": "2 Chronicles",
    "2Chr": "2 Chronicles",
    "2Ch": "2 Chronicles",
    "II Chron": "2 Chronicles",
    "II Chr": "2 Chronicles",
    "II Ch": "2 Chronicles",
    Ezra: "Ezra",
    Ezr: "Ezra",
    Ez: "Ezra",
    Neh: "Nehemiah",
    Ne: "Nehemiah",
    Esth: "Esther",
    Est: "Esther",
    Es: "Esther",
    Job: "Job",
    Jb: "Job",
    Ps: "Psalms",
    Psalm: "Psalms",
    Pslm: "Psalms",
    Psa: "Psalms",
    Psm: "Psalms",
    Pss: "Psalms",
    Prov: "Proverbs",
    Pro: "Proverbs",
    Prv: "Proverbs",
    Pr: "Proverbs",
    Eccl: "Ecclesiastes",
    Eccles: "Ecclesiastes",
    Eccle: "Ecclesiastes",
    Ecc: "Ecclesiastes",
    Ec: "Ecclesiastes",
    Qoh: "Ecclesiastes",
    Song: "Song of Songs",
    SOS: "Song of Songs",
    So: "Song of Songs",
    Cant: "Song of Songs",
    Isa: "Isaiah",
    Is: "Isaiah",
    Jer: "Jeremiah",
    Je: "Jeremiah",
    Lam: "Lamentations",
    La: "Lamentations",
    Ezek: "Ezekiel",
    Eze: "Ezekiel",
    Ezk: "Ezekiel",
    Dan: "Daniel",
    Da: "Daniel",
    Dn: "Daniel",
    Hos: "Hosea",
    Ho: "Hosea",
    Joel: "Joel",
    Jl: "Joel",
    Amos: "Amos",
    Am: "Amos",
    Ob: "Obadiah",
    Obad: "Obadiah",
    Jonah: "Jonah",
    Jnh: "Jonah",
    Jon: "Jonah",
    Mic: "Micah",
    Mc: "Micah",
    Nah: "Nahum",
    Na: "Nahum",
    Hb: "Habakkuk",
    Hab: "Habakkuk",
    Zeph: "Zephaniah",
    Zep: "Zephaniah",
    Zp: "Zephaniah",
    Hag: "Haggai",
    Hg: "Haggai",
    Zech: "Zechariah",
    Zec: "Zechariah",
    Zc: "Zechariah",
    Mal: "Malachi",
    Ml: "Malachi",
    Matt: "Matthew",
    Mt: "Matthew",
    Mark: "Mark",
    Mrk: "Mark",
    Mar: "Mark",
    Mk: "Mark",
    Mr: "Mark",
    Luke: "Luke",
    Luk: "Luke",
    Lk: "Luke",
    John: "John",
    Joh: "John",
    Jhn: "John",
    Jn: "John",
    Acts: "Acts",
    Act: "Acts",
    Ac: "Acts",
    Rom: "Romans",
    Ro: "Romans",
    Rm: "Romans",
    "1Cor": "1 Corinthians",
    "1 Cor": "1 Corinthians",
    "1 Co": "1 Corinthians",
    "1 Cor": "1 Corinthians",
    "1 Co": "1 Corinthians",
    "1Co": "1 Corinthians",
    "2Cor": "2 Corinthians",
    "2 Cor": "2 Corinthians",
    "2 Co": "2 Corinthians",
    "2Co": "2 Corinthians",
    "2Cor": "2 Corinthians",
    "2 Cor": "2 Corinthians",
    "1cor": "1 Corinthians",
    "1 cor": "1 Corinthians",
    "1 co": "1 Corinthians",
    "1co": "1 Corinthians",
    "2cor": "2 Corinthians",
    "2 cor": "2 Corinthians",
    "2 co": "2 Corinthians",
    "2co": "2 Corinthians",
    Gal: "Galatians",
    Ga: "Galatians",
    Eph: "Ephesians",
    Ephes: "Ephesians",
    Php: "Philippians",
    Pp: "Philippians",
    Col: "Colossians",
    Co: "Colossians",
    "1Thess": "1 Thessalonians",
    "1 Thess": "1 Thessalonians",
    "1Thes": "1 Thessalonians",
    "1 Thes": "1 Thessalonians",
    "1 Th": "1 Thessalonians",
    "1Th": "1 Thessalonians",
    "2Thess": "2 Thessalonians",
    "2 Thess": "2 Thessalonians",
    "2Thes": "2 Thessalonians",
    "2 Thes": "2 Thessalonians",
    "2 Th": "2 Thessalonians",
    "2Th": "2 Thessalonians",
    "1Tim": "1 Timothy",
    "1 Ti": "1 Timothy",
    "1 Tm": "1 Timothy",
    "1Tm": "1 Timothy",
    "1Tim": "1 Timothy",
    "2Tim": "2 Timothy",
    "2 Ti": "2 Timothy",
    "2Tm": "2 Timothy",
    "2 Tm": "2 Timothy",
    "2Tim": "2 Timothy",
    Titus: "Titus",
    Tt: "Titus",
    Tit: "Titus",
    Ti: "Titus",
    Phlm: "Philemon",
    Phm: "Philemon",
    Hebr: "Hebrews",
    Heb: "Hebrews",
    He: "Hebrews",
    Jas: "James",
    Jm: "James",
    James: "James",
    "1Pet": "1 Peter",
    "1pe": "1 Peter",
    "1 pe": "1 Peter",
    "1 Pe": "1 Peter",
    "1Pet": "1 Peter",
    "2Pet": "2 Peter",
    "2 Pe": "2 Peter",
    "2 Pe": "2 Peter",
    "2Pet": "2 Peter",
    "1John": "1 John",
    "1 Jo": "1 John",
    "1Jo": "1 John",
    "1 Jn": "1 John",
    "1Jn": "1 John",
    "1John": "1 John",
    "2John": "2 John",
    "2 Jo": "2 John",
    "2 Jn": "2 John",
    "2Jo": "2 John",
    "2Jn": "2 John",
    "2John": "2 John",
    "2 John": "2 John",
    "3John": "3 John",
    "3 Jo": "3 John",
    "3 Jn": "3 John",
    "3Jo": "3 John",
    "3Jn": "3 John",
    "3 John": "3 John",
    Jude: "Jude",
    Jud: "Jude",
    Jd: "Jude",
    Rev: "Revelation",
    Re: "Revelation",
    Mt: "Matthew",
    Mc: "Mark",
    Act: "Acts",
    "1K": "1 Corinthians",
    "2K": "2 Corinthians",
    Kol: "Colossians",
    "1Th": "1 Thessalonians",
    "2Th": "2 Thessalonians",
    "1T": "1 Timothy",
    "2T": "2 Timothy",
    Tt: "Titus",
    Phm: "Philemon",
    Jc: "James",
    "1P": "1 Peter",
    "2P": "2 Peter",
    "1J": "1 John",
    "2J": "2 John",
    "3J": "3 John",
    Jd: "Jude",
    Ap: "Revelation",
}

module.exports = abbrevations
