module.exports = {
    Genesis: require("./chapter_verses/genesis"),
    Exodus: require("./chapter_verses/exodus"),
    Leviticus: require("./chapter_verses/leviticus"),
    Numbers: require("./chapter_verses/numbers"),
    Deuteronomy: require("./chapter_verses/deuteronomy"),
    Joshua: require("./chapter_verses/joshua"),
    Judges: require("./chapter_verses/judges"),
    Ruth: require("./chapter_verses/ruth"),
    "1 Samuel": require("./chapter_verses/1samuel"),
    "2 Samuel": require("./chapter_verses/2samuel"),
    "1 Kings": require("./chapter_verses/1kings"),
    "2 Kings": require("./chapter_verses/2kings"),
    "1 Chronicles": require("./chapter_verses/1chronicles.js"),
    "2 Chronicles": require("./chapter_verses/2chronicles.js"),
    Ezra: require("./chapter_verses/ezra.js"),
    Nehemiah: require("./chapter_verses/nehemiah"),
    Esther: require("./chapter_verses/esther.js"),
    Job: require("./chapter_verses/job"),
    Psalms: require("./chapter_verses/psalms"),
    Proverbs: require("./chapter_verses/proverbs"),
    Ecclesiastes: require("./chapter_verses/ecclesiastes"),
    "Song of Songs": require("./chapter_verses/songs"),
    Isaiah: require("./chapter_verses/isaiah"),
    Jeremiah: require("./chapter_verses/jeremiah"),
    Lamentations: require("./chapter_verses/lamentations"),
    Ezekiel: require("./chapter_verses/ezekiel"),
    Daniel: require("./chapter_verses/daniel"),
    Hosea: require("./chapter_verses/hosea"),
    Joel: require("./chapter_verses/joel"),
    Amos: require("./chapter_verses/amos"),
    Jonah: require("./chapter_verses/jonah"),
    Micah: require("./chapter_verses/micah"),
    Nahum: require("./chapter_verses/nahum"),
    Habakkuk: require("./chapter_verses/habakkuk.js"),
    Zephaniah: require("./chapter_verses/zephaniah"),
    Haggai: require("./chapter_verses/haggai"),
    Zechariah: require("./chapter_verses/zechariah"),
    Malachi: require("./chapter_verses/malachi"),
    Matthew: require("./chapter_verses/matthew"),
    Mark: require("./chapter_verses/mark"),
    Luke: require("./chapter_verses/luke"),
    John: require("./chapter_verses/john"),
    Acts: require("./chapter_verses/acts"),
    Romans: require("./chapter_verses/romans"),
    "1 Corinthians": require("./chapter_verses/1corinthians"),
    "2 Corinthians": require("./chapter_verses/2corinthians"),
    Galatians: require("./chapter_verses/galatians"),
    Ephesians: require("./chapter_verses/ephesians"),
    Philippians: require("./chapter_verses/philippians"),
    Colossians: require("./chapter_verses/colossians"),
    "1 Thessalonians": require("./chapter_verses/1thessalonians"),
    "2 Thessalonians": require("./chapter_verses/2thessalonians"),
    "1 Timothy": require("./chapter_verses/1timothy"),
    "2 Timothy": require("./chapter_verses/2timothy"),
    Titus: require("./chapter_verses/titus"),
    Hebrews: require("./chapter_verses/hebrews"),
    James: require("./chapter_verses/james"),
    "1 Peter": require("./chapter_verses/1peter"),
    "2 Peter": require("./chapter_verses/2peter"),
    "1 John": require("./chapter_verses/1john"),
    Revelation: require("./chapter_verses/revelation"),
}
