const versified = {
    Genesis: require("./versifications/genesis"),
    Exodus: require("./versifications/exodus"),
    Leviticus: require("./versifications/leviticus"),
    Numbers: require("./versifications/numbers"),
    Deuteronomy: require("./versifications/deuteronomy"),
    Joshua: require("./versifications/joshua"),
    "1 Samuel": require("./versifications/1samuel"),
    "2 Samuel": require("./versifications/2samuel"),
    "1 Kings": require("./versifications/1kings"),
    "1 Chronicles": require("./versifications/1chronicles"),
    "2 Chronicles": require("./versifications/2chronicles"),
    Nehemiah: require("./versifications/nehemiah"),
    Job: require("./versifications/job"),
    Psalms: require("./versifications/psalms"),
    Proverbs: require("./versifications/proverbs"),
    Ecclesiastes: require("./versifications/ecclesiastes"),
    "Song of Songs": require("./versifications/song"),
    Isaiah: require("./versifications/isaiah"),
    Jeremiah: require("./versifications/jeremiah"),
    Ezekiel: require("./versifications/ezekiel"),
    Daniel: require("./versifications/daniel"),
}

module.exports = versified
